additionalPrometheusRulesMap:
  myrulename:
    groups:
    - name: myrecordingrules
      rules:
      - record: go_goroutines
        expr: go_goroutines{job="dummy-exporter"}>1
    - name: myalertingrules
      rules:
      - alert: Dummy metric above the limit
        expr: go_goroutines{job="dummy-exporter"}>1
        for: 1m
        labels:
          severity: warning
        annotations:
          message: '{{ $labels.instance }} in troubles.'
          runbook_url: https://stackoverflow.com/

grafana:
  sidecar:
    datasources:
      #url: "http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
      url: "http://monitoring-kube-prometheus-prometheus:9090"

prometheus:
  additionalServiceMonitors:
    - name: servicemonitor-dummy-app
      additionalLabels:
        my-custom-label: my-custom-value
      selector:
        matchLabels:
          app: dummy-exporter
      namespaceSelector:
        matchNames:
          - default
      endpoints:
        - port: http
          path: /metrics
  # additionalPodMonitors:
  #   - name: dummy-app
  #     additionalLabels:
  #       my-custom-label: my-custom-value
  #     selector:
  #       app: dummy-exporter
  #     namespaceSelector:
  #       matchNames:
  #         - default
  #     endpoints:
  #       - port: http
  #         path: /metrics
  #     podMetricsEndpoints:
  #       - port: http
  #         path: /metrics


